### ISSUE TITLE
mac M2 can not install binary

### ISSUE THREAD

**Issue by cuihuabjn5789** [ionet-official/io_launch_binaries#10]
![M2](https://github.com/ionet-official/io_launch_binaries/assets/79395045/837299e8-ae39-4fea-97ff-6859c8dcaf08)
when I use the code to install the binary , it shows the issue as the picture. I had tried many times , ir was not be fixed .

**Comment by smiraldr** [comment]
This error typically means that the curl command was unable to establish a connection to the GitHub server on port 443, which is the standard port for HTTPS connections. Please check your firewall settings and internet connection or use a VPN if needed. P.S. I see that you might be from china mainland - we currently don't allow devices from this location due to legal issues.
